# no-unhandled-function

Rule that enforces any function call that can throw an error to be inside a try...catch block

Currently it's just an idea inspired by the no-unhandled rule by the ex lib:

https://github.com/Akronae/eslint-plugin-exception-handling/tree/main